### ISSUE TITLE
A few grammatical errors

### ISSUE THREAD

**Issue by benyamin-noori** [zeeshanu/learn-regex#29]
I noticed there are a few grammatical errors:

In section 4. Lookaround this part: 
"which means: get all the **numbers which contains** . character **and preceded** by $ character." 
Should be modified to: 
"which means: get all the **numbers which contain**. character **and are preceded** by $ character."

Also, in section 2.5:
"As we discussed before that in regular expression if we put a quantifier after a character **than** it will repeat the preceding character."
Should be modified to:
"As we discussed before that in regular expression if we put a quantifier after a character **then** it will repeat the preceding character."

**Comment by falaktheoptimist** [comment]
Fixed with #27

**Comment by priyadhoundiyal** [comment]
Not OP but can we reopen this? I found a few more grammatical errors.
"Imagine you are writing an application and you want to set the rules **when user choosing their** username. We want **the username can contains letter, number**, underscore and hyphen."
should be modified to:
"Imagine you are writing an application and you want to set the rules **for when a user chooses** their username. We want **to allow the username to contain letters, numbers**, underscore and hyphen."

In section 1, I think "A regular expression is just a pattern of **letters and digits**" should be replaced with:
 "A regular expression is just a pattern of **characters**" since characters is generic and can be used to represent letters, digits and symbols.

In section 2, 
"Some meta characters have a special meaning **that** are written **inside the square brackets**" 
should be replaced  with 
"Some meta characters have a special meaning **and** are written **inside square brackets**"

In section 2.8
"In regular expressions, **to check if the matching symbol is the starting symbol or ending symbol of the input string for this purpose we use anchors**" should be replaced by
"In regular expressions, **we use anchors to check if the matching symbol is the starting symbol or ending symbol of the input string**"
