### ISSUE TITLE
Email regex misleading

### ISSUE THREAD

**Issue by DwordPtr** [zeeshanu/learn-regex#7]
parsing emails with regex is hard and complicated. There are many solutions that work _almost_ fine but can cause problems on edge cases. 

I think replacing the regex with full rfc 5322 is obviously ridiculous but maybe adding a note would be a good idea.

**Comment by t3rminus** [comment]
This should definitely be noted. For instance, the regex given will fail for sites with a `.museum` TLD, due to the 4-character limit on TLDs.

A more general solution might simply be `^\S+@\S+$`, since there isn't even a guarantee the address' domain will contain a `.` (for instance, when sending to localhost).

**Comment by dikti** [comment]
Also, it doesn't allow `+`. I always use *myaddr+randomstring@mydomain.com*, which is totally valid.

**Comment by dmage** [comment]
RFC 6530 allows to use `чебурашка@ящик-с-апельсинами.рф`.
